<?php


function rbkc_nd_domain_add($subdomain, $sitename, $domain_theme) {

  rbkc_nd_domain_add_domain($subdomain, $sitename);
  rbkc_nd_domain_add_subfolder($subdomain, $sitename);

  $domain = array_filter(domain_domains(), function($domain) use ($subdomain) {
    return $domain['subdomain'] == $subdomain ? $domain : false;
  });
  $domain_id = (int) reset($domain)['domain_id'];

  if ($domain_id) {
    rbkc_nd_domain_set_parent($subdomain, $domain_id);

    if (!empty($domain_theme)) {
      rbkc_nd_domain_set_theme($domain_id, $domain_theme);
    }
  }
}

function rbkc_nd_domain_add_domain($subdomain, $sitename) {
  $start_weight = (int) db_query("SELECT weight FROM {domain} ORDER BY weight DESC")->fetchField();
  $record = array(
    'subdomain' => strtolower($subdomain),
    'sitename' => $sitename,
    'valid' => 1,
    'scheme' => 'https',
    'weight' => $start_weight + 1,
    'is_default' => 0,
  );
  if (!empty($record['is_default'])) {
    $error = domain_check_response($record, TRUE);
    if ($error) {
      if (drupal_is_cli()) {
        return drush_set_error('domain', $error);
      } else {
        print_r($error);
        return false;
      }
    }
  }
  $domain = domain_save($record, $record);
  if (isset($domain['domain_id'])) {
    if (drupal_is_cli()) {
      drush_print(dt('Created @domain for @sitename.', array('@domain' => $domain['subdomain'], '@sitename' => $domain['sitename'])));
    } else {
      print t('Created @domain for @sitename.', array('@domain' => $domain['subdomain'], '@sitename' => $domain['sitename']));
    }
  }
  else {
    if (drupal_is_cli()) {
      drush_print(dt('The request could not be completed.'));
    } else {
      print t('The request could not be completed.');
    }
  }

}

function rbkc_nd_domain_add_subfolder($subdomain, $sitename) {
  $check_subdomain = subfolders_domain_valid($subdomain, $error_list, 'domain_form');

  $error_list = $check_subdomain['error_list'];
  if (!empty($error_list)) {
    if (drupal_is_cli()) {
      drush_set_error('subdomain', implode('<br />', $error_list));
    } else {
      print_r($error_list);
    }
  }

  $form = $form_state = array();
  subfolders_domain_form_submit($form, $form_state);
}

function rbkc_nd_domain_set_parent($subdomain, $domain_id) {

  $default_id = domain_default_id();

  db_insert('subfolders_domain')
    ->fields(array(
      'site' => $subdomain,
      'parent_id' => $default_id,
      'language' => '',
      'domain_id' => $domain_id,
    ))
    ->execute();

}

function rbkc_nd_domain_set_theme($domain_id, $domain_theme) {

  $theme = $domain_theme;

  // Set all themes in this domain to null status.
  db_update('domain_theme')
    ->fields(array(
      'status' => 0,
    ))
    ->condition('domain_id', $domain_id)
    ->execute();
  // Now activate the selected theme.
  // This lookup returns -1 on failure.
  $check = domain_theme_lookup($domain_id, $theme);
  // Update.
  if ($check != -1) {
    db_update('domain_theme')
      ->fields(array(
        'status' => 1,
      ))
      ->condition('domain_id', $domain_id)
      ->condition('theme', $theme)
      ->execute();
  }
  // Insert.
  else {
    db_insert('domain_theme')
      ->fields(array(
        'domain_id' => $domain_id,
        'theme' => $theme,
        'settings' => '',
        'status' => 1,
        'filepath' => '',
      ))
      ->execute();
  }
  cache_clear_all();
}
